version: '3.4'

services:
  patchimg:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_TOOLS=yes
      target: buildimg
    image: app_image

  db:
    container_name: db
    build:
      context: .
      dockerfile: dev/database/Dockerfile
    command: 'postgres -c config_file=/opt/app-root/src/postgresql-cfg/custom.conf'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file:
      - ./conf/database.env
    security_opt:
      - label=disable

  db_admin:
    container_name: db_admin
    image: app_image
    env_file:
      - ./conf/common.env
      - ./conf/database_common.env
      - ./conf/database_admin.env
      - ./conf/gorun.env
    command: ./database_admin/entrypoint.sh
    depends_on:
      - db
      - patchimg
    volumes:
      - ./:/go/src/app
    security_opt:
      - label=disable

  db_feed:
    container_name: db_feed
    image: app_image
    env_file:
      - ./conf/test.env
      - ./conf/gorun.env
    command: ./scripts/feed_db.sh
    depends_on:
      - db
      - patchimg
    volumes:
      - ./:/go/src/app
    security_opt:
      - label=disable

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: unless-stopped
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    environment:
      REDIS_PASSWORD: redis_pwd
    ports:
      - 6379:6379

  platform:
    container_name: platform
    image: app_image
    command: ./scripts/entrypoint.sh platform
    restart: unless-stopped
    depends_on:
      - patchimg
    ports:
      - 9001:9001

  manager:
    container_name: manager
    image: app_image
    env_file:
      - ./conf/common.env
      - ./conf/database_common.env
      - ./conf/manager.env
      - ./conf/gorun.env
    command: ./scripts/entrypoint.sh manager
    ports:
      - 8080:8080
      - 9080:9080 # metrics
    depends_on:
      - db
      - platform
      - patchimg
    volumes:
      - ./:/go/src/app
    security_opt:
      - label=disable

  exporter:
    container_name: exporter
    image: app_image
    env_file:
      - ./conf/common.env
      - ./conf/database_common.env
      - ./conf/exporter.env
      - ./conf/gorun.env
    command: ./scripts/entrypoint.sh exporter
    ports:
      - 8083:8083
    restart: unless-stopped
    depends_on:
      - db
      - platform
      - patchimg
      - redis
    volumes:
      - ./:/go/src/app
    security_opt:
      - label=disable

volumes:
  db-data:
